
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Nahian
 */
public class History extends javax.swing.JFrame {

    String id, name, bday;

    public History() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ta10 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        ta0 = new javax.swing.JTextField();
        ta1 = new javax.swing.JTextField();
        ta2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        ta3 = new javax.swing.JTextField();
        ta4 = new javax.swing.JTextField();
        ta5 = new javax.swing.JTextField();
        ta6 = new javax.swing.JTextField();
        ta7 = new javax.swing.JTextField();
        ta8 = new javax.swing.JTextField();
        ta9 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("View All History ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Delete All");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        ta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ta3ActionPerformed(evt);
            }
        });

        ta7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ta7ActionPerformed(evt);
            }
        });

        ta8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ta8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jButton1)
                .addGap(74, 74, 74)
                .addComponent(jButton2)
                .addContainerGap(113, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ta4, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ta7, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ta2)
                        .addComponent(ta1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                        .addComponent(ta0, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                        .addComponent(ta5)
                        .addComponent(ta6)
                        .addComponent(ta8)
                        .addComponent(ta3, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                        .addComponent(ta9)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(29, 29, 29)
                .addComponent(ta0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(ta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ta4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ta5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ta6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ta7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ta8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ta9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");

            Connection conn = DriverManager.getConnection("jdbc:odbc:Database2");
            java.sql.Statement st = conn.createStatement();
            String sql = "Select * from Table1";
            ResultSet rs = st.executeQuery(sql);
            
            rs.next(); {
//                ta0.setText(rs.getString(1)+"\t"+rs.getString(2));
//                ta1.setText(rs.getString(1)+"\t"+rs.getString(2));
//                ta2.setText(rs.getString(1)+"\t"+rs.getString(2));
                
                id = rs.getString("id");
                name = rs.getString("Address");
                ta0.setText(id + "\t" + name);
                

            }
            rs.next(); {
//                ta0.setText(rs.getString(1)+"\t"+rs.getString(2));
//                ta1.setText(rs.getString(1)+"\t"+rs.getString(2));
//                ta2.setText(rs.getString(1)+"\t"+rs.getString(2));
                
                id = rs.getString("id");
                name = rs.getString("Address");
                ta1.setText(id + "\t" + name);
                

            }
            rs.next(); {
                
                
                id = rs.getString("id");
                name = rs.getString("Address");
                ta2.setText(id + "\t" + name);
                

            }
            rs.next(); {
                
                
                id = rs.getString("id");
                name = rs.getString("Address");
                ta3.setText(id + "\t" + name);
                

            }
            rs.next(); {
                
                
                id = rs.getString("id");
                name = rs.getString("Address");
                ta4.setText(id + "\t" + name);
                

            }
            rs.next(); {
                
                
                id = rs.getString("id");
                name = rs.getString("Address");
                ta5.setText(id + "\t" + name);
                

            }
            rs.next(); {
                
                
                id = rs.getString("id");
                name = rs.getString("Address");
                ta6.setText(id + "\t" + name);
                

            }
            rs.next(); {
                
                
                id = rs.getString("id");
                name = rs.getString("Address");
                ta7.setText(id + "\t" + name);
                

            }
            rs.next(); {
                
                
                id = rs.getString("id");
                name = rs.getString("Address");
                ta8.setText(id + "\t" + name);
                

            }
            rs.next(); {
                
                
                id = rs.getString("id");
                name = rs.getString("Address");
                ta9.setText(id + "\t" + name);
                

            }
            
            
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Connection con;
		try
		{
			Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
			con = DriverManager.getConnection("jdbc:odbc:Database2");
			String sql = "delete from Table1 where id = '"+id+"'";
			Statement statement = con.createStatement();
			statement.execute(sql);
                        ta0.setText("");
                        ta1.setText("");
                        ta2.setText("");
                        ta3.setText("");
                        ta4.setText("");
                        ta5.setText("");
                        ta6.setText("");
                        ta7.setText("");
                        ta8.setText("");
                        ta9.setText("");
                        
			
		}
		catch(ClassNotFoundException | SQLException e)
		{
			//createMessageBox(e.getMessage());
		}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ta3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ta3ActionPerformed

    private void ta7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ta7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ta7ActionPerformed

    private void ta8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ta8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ta8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public  void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new History().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField ta0;
    private javax.swing.JTextField ta1;
    private javax.swing.JTextField ta10;
    private javax.swing.JTextField ta2;
    private javax.swing.JTextField ta3;
    private javax.swing.JTextField ta4;
    private javax.swing.JTextField ta5;
    private javax.swing.JTextField ta6;
    private javax.swing.JTextField ta7;
    private javax.swing.JTextField ta8;
    private javax.swing.JTextField ta9;
    // End of variables declaration//GEN-END:variables
}
